apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-app
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pilot-app
  template:
    metadata:
      labels:
        app: pilot-app
    spec:
      containers:
        - name: pilot-app
          image: kirandeep/pilot-app
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred