apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-static-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/Users/kirandeep/kd"
