apiVersion: v1
kind: Service
metadata:
  name: pilot-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: pilot-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30003


