apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-app
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pilot-app
  template:
    metadata:
      labels:
        app: pilot-app
    spec:
      volumes:
        - name: webcontent
          persistentVolumeClaim:
            claimName: pvc-nfs-static-data
      containers:
        - name: pilot-app
          image: kirandeep/pilot-app
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: webcontent
              mountPath: "/kd"
      imagePullSecrets:
        - name: regcred